import type { Metadata } from "next";
import { Inter, Inknut_Antiqua } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], weight: "400" });

const inknutAntiqua = Inknut_Antiqua({ subsets: ["latin"], weight: "400",variable: "--font-inknut" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  antialiased  ${inknutAntiqua.variable}`}
      >
       {children}
      </body>
    </html>
  );
}
